services:
  product-api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: product-api
    ports:
      - "8080:8080"
    networks:
      - app-network

  locust:
    image: locustio/locust:latest
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/home/locust/locustfile.py
    command: -f /home/locust/locustfile.py --host=http://product-api:8080
    networks:
      - app-network
    depends_on:
      - product-api

networks:
  app-network:
    driver: bridge
